### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by Shkeffy** [WolvTMG/TMG-SB#1]
Takes pretty long to install all requirements, I'll check back later to tell you if the selfbot works.

**Comment by WolvTMG** [comment]
Alright, thanks for letting me know.

**Comment by WolvTMG** [comment]
> Takes pretty long to install all requirements, I'll check back later to tell you if the selfbot works.

Alright, thanks for letting me know.

**Comment by Shkeffy** [comment]
Wow, it takes a WHILE.

> > Takes pretty long to install all requirements, I'll check back later to tell you if the selfbot works.
> 
> Alright, thanks for letting me know.

**Comment by Shkeffy** [comment]
Omg, it's still going.

**Comment by Shkeffy** [comment]
I re-cloned it, I'm going to see if you can just install the packages from the packages menu :/

**Comment by WolvTMG** [comment]
Alright, lemme know how it goes.

**Comment by Shkeffy** [comment]
I don't think it works, when you individually try to install everything, once you hit 'colorama', it does the errror message: 
![image](https://user-images.githubusercontent.com/97449528/166162528-15ed3afc-f2ea-4bee-b15c-111b829e8880.png)
I'm going to try doing the install requirements again :/

**Comment by WolvTMG** [comment]
Hmm, I'm not sure why you're getting error codes on the startup file. I ran the startup file on a VM and it worked just fine for me.
